### ISSUE TITLE
webpack4构建器分工

### ISSUE THREAD

**Issue by cpselvis** [feflow/builder-webpack4#1]
任务名称 | 负责人 | 开发状态 | 如何升级 | 完成时间
-- | -- | --| --| --
html-webpack-plugin | tickli | 完成 |  平滑升级到4.0.0-beta.1 |  2018.10.10
extract-text-webpack-plugin | erwinliu | 完成 | mini-css-extract-plugin替代 | 2018.10.10
clean-webpack-plugin | leoytliu | 完成 | 平滑升级到0.1.19|2018.10.10
html-webpack-externals-plugin | lewischeng | 完成 |  平滑升级到1.1.0-rc.7  | 2018.10.10
html-inline-css-webpack-plugin | tickli | 完成 |  代替 html-webpack-inline-source-plugin | 2018.10.11
replace-bundle-webpack-plugin | erwinliu | 完成 | 插件已移除|2018.10.10
html-string-replace-webpack-plugin | leoytliu | 完成 | 已移除，原来是为了替换html中的cdn目录问题，现在不用了|2018.10.10
string-replace-webpack-plugin | lewischeng | 开发中 | 
webpack-subresource-integrity | tickli | 完成 |平滑升级到1.1.0 | 2018.10.11
offline-webpack-plugin | erwinliu | 完成 | 通过改写 API 支持 webpack 4|2018.10.10
Happypack | lewischeng | 完成 | 使用thread-loader替代 |  2018.10.10
webpack-parallel-uglify-plugin | tickli | 完成 |  目前的uglifyjs-webpack-plugin可以通过配置parallel=true直接支持 | 
webpack-deep-scope-analysis-plugin | leoytliu | 开发中 | 
SSR插件开发 | lewischeng | 开发中 | 
Prerender插件开发 | leoytliu | 开发中 | 
PWA插件开发 | tickli | 开发中 | 
支持optional chaining语法糖 | lewischeng | 开发中 | 
废弃对Sass支持，仅支持Less | erwinliu | 完成 |  已经去掉 |

**Comment by LeoEatle** [comment]
还有`CommonChunk`，这个插件在webpack4已内置，需要改动配置。

**Comment by LeoEatle** [comment]
`webpack-parallel-uglify-plugin`已不再需要，目前的`uglifyjs-webpack-plugin`可以通过配置`parallel=true`直接支持
![image](https://user-images.githubusercontent.com/14247110/46736130-cb3c8000-ccca-11e8-80fd-501f3c2b8a62.png)

**Comment by vabaly** [comment]
离线包插件通过同步 `webpack 4` 的 `API` 达到支持 `webpack 4` 的效果，部分代码如下：

改动前：

```js
compiler.plugin('emit', function(compilation, callback) {
	// assets from child compilers will be included in the parent
	// so we should not run in child compilers
	if (this.isChild()) {
		callback();
		return;
	}
        // ...
}
```

改动后：

```js
(
	compiler.hooks
	? compiler.hooks.emit.tapAsync.bind(compiler.hooks.emit, ZipPlugin.name)
	: compiler.plugin.bind(compiler, 'emit')
)(function(compilation, callback) {
	// assets from child compilers will be included in the parent
	// so we should not run in child compilers
	var isChild = compilation.compiler && compilation.compiler.isChild
		? compilation.compiler.isChild()
		: this.isChild()
	if (isChild) {
		callback();
		return;
	}
        // ...
}
```

webpack 4 的 `emit` 放在了 `hooks` 里面
