### ISSUE TITLE
webpack版本导致mini-css-extract-plugin出现错误

### ISSUE THREAD

**Issue by LeoEatle** [feflow/builder-webpack4#12]
虽然`builder-webpack4`已经指定版本`"webpack": "^4.20.2"`
但是在构建中我们的`webpack`版本为`.feflow`目录中`node_modules`的版本，这个版本低于4
这样会导致出现如下错误

![image](https://user-images.githubusercontent.com/14247110/49518895-b3543780-f8da-11e8-9f1b-93e761e05962.png)

相关issue已经提到是因为webpack版本问题
#https://github.com/webpack-contrib/mini-css-extract-plugin/issues/69

所以我们需要找到一种方式能够让feflow使用builder中依赖的webpack，否则feflow永远只有一个版本的webpack可以用。

**Comment by LeoEatle** [comment]
这个问题是因为npm会`扁平化`安装，导致`mini-css-extract-plugin`被安装到了`.feflow`目录下
它寻找`webpack`的时候，只会找到`.feflow`下的`node_modules`，而不是`builder-webpack4`下的。
为了避免这个问题，建议feflow可以使用`--global-style`来安装builder和脚手架

> The --global-style argument will cause npm to install the package into your local node_modules folder with the same layout it uses with the global node_modules folder. Only your direct dependencies will show in node_modules and everything they depend on will be flattened in their node_modules folders. This obviously will eliminate some deduping.

[官方文档](https://docs.npmjs.com/cli/install) 提到了如果想只安装到local node_modules，可以使用这个参数。

这样的话各个builder和脚手架的依赖不会互相干扰，永远优先在自己的目录下查找依赖。

**Comment by cpselvis** [comment]
这个方案很棒，后面feflow安装时加上这个参数，避免相互干扰

**Comment by LeoEatle** [comment]
这个问题已经解决，close
