### ISSUE TITLE
inline的CSS没有压缩

### ISSUE THREAD

**Issue by cpselvis** [feflow/builder-webpack4#18]
对应的业务链接：http://qun.qq.com/qunpay/activity/goldpig/index.html?_wv=49152&_wwv=4
![image](https://user-images.githubusercontent.com/18289264/51785151-7e53bb00-218e-11e9-8d01-d8a5e062b30f.png)

**Comment by LeoEatle** [comment]
可能需要inline插件提供一下？

**Comment by cpselvis** [comment]
已经 Fix，是因为 css-loader@1.0.0 之后不支持 css 压缩了，采用optimize-css-assets-webpack-plugin去做
