### ISSUE TITLE
构建出来的react依赖script内integrity为null

### ISSUE THREAD

**Issue by jhaofan** [feflow/builder-webpack4#20]
![图片](https://user-images.githubusercontent.com/26264445/54268380-031b5c80-45b6-11e9-9b5e-f0f648881c1b.png)
![图片](https://user-images.githubusercontent.com/26264445/54268463-31993780-45b6-11e9-9e25-f78b82449c94.png)

**Comment by cpselvis** [comment]
这个我处理下

**Comment by cpselvis** [comment]
v0.0.15 已经修复，将 webpack-subsource 设置成1.1.0版本

**Comment by cpselvis** [comment]
可以通过这个工具生成线上的 integrity, https://laysent.github.io/sri-hash-generator/
