### ISSUE TITLE
离线包插件支持webpack4

### ISSUE THREAD

**Issue by LeoEatle** [feflow/builder-webpack4#4]
资源目录结构根据这个[PR](https://github.com/feflow/builder-webpack4/pull/3)已支持

目前测试用例通过2/3，只剩离线包插件支持webpack4。

**Comment by cpselvis** [comment]
这个是 @i-solar 负责

**Comment by vabaly** [comment]
已通过升级支持

**Comment by cpselvis** [comment]
v0.1.0的离线包插件支持webpack4
