### ISSUE TITLE
typescript的支持

### ISSUE THREAD

**Issue by LeoEatle** [feflow/builder-webpack4#8]
1. 现在还在用happypack连接ts-loader支持ts，需要改为thread-loader，并且加上[fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin)
2. 测试用的项目无论是这个项目里面还是now那个项目，都还没有ts文件，这个测试用例没测到，需要补充
3. ts-loader需要配置tsconfig，需要脚手架支持

**Comment by cpselvis** [comment]
暂时先不用支持TS，目前的团队技术栈不包括TS，后续如果团队技术栈有变化再进行支持。
